import JSZip from 'jszip'
import { readStoredFile } from '@/lib/providers/storage'
import { renderLandingPageHtml, type RenderLandingPageInput } from './renderer'

export interface LandingZipInput extends RenderLandingPageInput {
  publishedSlug?: string | null
}

export function landingZipFileName(title: string): string {
  const slug =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'book-website'
  return `${slug}-landing-website.zip`
}

export async function buildLandingZip(
  input: LandingZipInput,
  read: typeof readStoredFile = readStoredFile
): Promise<Buffer> {
  const zip = new JSZip()

  // 1. Generate standalone HTML page
  const htmlContent = renderLandingPageHtml(input)
  zip.file('index.html', htmlContent)

  // 2. Include cover asset if present
  if (input.coverUrl) {
    try {
      const cover = await read(input.coverUrl)
      const ext = cover.contentType.includes('png') ? 'png' : 'jpg'
      zip.file(`assets/cover.${ext}`, cover.data)
    } catch {
      // Ignore
    }
  }

  // 3. Deployment Readme
  const readme = [
    `# ${input.title} — Book Landing Website`,
    '',
    'This is a complete, self-contained, responsive website package generated by **Publisher Toolkit**.',
    '',
    '## How to Deploy',
    '',
    '### Option 1: Vercel or Netlify (Drag and Drop)',
    '1. Unzip this folder.',
    '2. Drag and drop the folder directly into the Netlify Drop or Vercel dashboard.',
    '3. Your custom book landing page will be instantly live with SSL!',
    '',
    '### Option 2: GitHub Pages',
    '1. Create a repository on GitHub.',
    '2. Push `index.html` to the `main` branch.',
    '3. Enable GitHub Pages under Repository Settings -> Pages.',
    '',
    '### Option 3: Traditional Web Hosting (cPanel / Apache / Nginx)',
    'Upload `index.html` directly to your `public_html` or website root directory.',
  ].join('\n')

  zip.file('README.md', readme)

  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
}
